spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework: DEBUG   # Debug Spring Framework logs
    org.hibernate.SQL: DEBUG       # Debug Hibernate SQL queries
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # Debug SQL parameter binding
    com.gamax.userservice: DEBUG   # Debug logs for your application (replace with your package name)

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000  # 1h in milliseconds
